### ISSUE TITLE
Scoreboards are not being reverted on arena exit.

### ISSUE THREAD

**Issue by mibby** [Shynixn/BlockBall#10]
BlockBall v3.8.0

When players join a game and get kicked out on end, their former scoreboard is wiped. In my case, I colorize displaynames based on permission groups so players end up with a white nametag above their head after they play a game of BlockBall. Is there any way to preserve and load the old player's scoreboard when they leave the arena?

```
    scoreboard:
      enabled: true
      title: §a§lBlockBall
      items:
        red: §cTeam Red
        blue: §9Team Blue
        time: §eTime
```

In addition, is it possible to colorize the player's nametag above their head based on the team they are a part of if the scoreboard is disabled (due to wanting to use bossbar instead)?
